<a href="https://colab.research.google.com/github/demigod1208/numpy-practice/blob/main/Array%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#array manipullation

# reshape()

import numpy as np
import random as r

a = np.arange(12)
print(a)
a.reshape(4,3)
np.reshape(a,(6,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
# ravel()

a = np.arange(16)
a = np.reshape(a,(2,8))
print(a)
print()
b =a.ravel()
print(b)
print()
d = a.reshape(-1)
print(d)
print()

# flatten()
c = a.flatten()
print(c)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
# transpose

a = np.arange(32).reshape(8,4)
print(a)
print()
b = np.transpose(a)
print(b)
print()
c = a.T
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [6]:
# expand_dims_ () & Squeeze()

a = np.arange(32).reshape(8,4)
print(a)
print(a.shape)
print()
b = np.array([[[1],[1],[3]],[[2],[2],[7]],[[12],[32],[43]]])
print(b)
print(b.shape)
print(b.ndim)
print()

# expand dims()

e = np.expand_dims(a,axis=0)
print(e.shape)
print()

r = np.expand_dims(a,axis=1)
print(r.shape)
print()

s = np.squeeze(e,axis=0)
print(s.shape)
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
(8, 4)

[[[ 1]
  [ 1]
  [ 3]]

 [[ 2]
  [ 2]
  [ 7]]

 [[12]
  [32]
  [43]]]
(3, 3, 1)
3

(1, 8, 4)

(8, 1, 4)

(8, 4)



In [11]:
#Joining And Spliting Array
import random as r

ma = np.arange(24).reshape(6,4)
print(ma)
print()
mb = [r.randint(0,50) for i in range(24)]
mb = np.array(mb).reshape(6,4)
print(mb)
print()
# joining of array

#concatenate()

con = np.concatenate((ma,mb),axis=None)
print("concatenate with axis is none",con)
print()
con1 = np.concatenate((ma,mb),axis=1)
print("concatenate with axis is 1",con1)
print()
con2 = np.concatenate((ma,mb),axis=0)
print("concatenate with axis is 2",con2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[42 22 38 21]
 [10 39  6 30]
 [32 30  8  3]
 [38  8  5 17]
 [14 49  3 46]
 [47  4 25 33]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 42 22 38 21 10 39  6 30 32 30  8  3 38  8  5 17 14 49  3 46 47  4 25 33]

[[ 0  1  2  3 42 22 38 21]
 [ 4  5  6  7 10 39  6 30]
 [ 8  9 10 11 32 30  8  3]
 [12 13 14 15 38  8  5 17]
 [16 17 18 19 14 49  3 46]
 [20 21 22 23 47  4 25 33]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [42 22 38 21]
 [10 39  6 30]
 [32 30  8  3]
 [38  8  5 17]
 [14 49  3 46]
 [47  4 25 33]]


In [22]:
#joining array

#stack
ma = [r.randint(0,50) for i in range(24)]
ma = np.array(ma).reshape(6,4)
print(ma)
print()
mb = [r.randint(0,50) for i in range(24)]
mb = np.array(mb).reshape(6,4)
print(mb)
print()

#stack
stc = np.stack((ma,mb))
print(" stack with axis is none",stc)
print()


stc1 = np.stack((ma,mb),axis=0)
print(" stack with axis is 0",stc1)
print()


stc2 = np.stack((ma,mb),axis=1)
print(" stack with axis is one",stc2)
print()


[[26  6 13 44]
 [24  3  6 37]
 [16  6 22 14]
 [47  1 42 50]
 [48 50 50 22]
 [ 5 48 36 22]]

[[37 29 19 23]
 [22 50  5 32]
 [27 30 18 21]
 [ 2  8 34 12]
 [31 24 23 21]
 [ 4 47 38 27]]

 stack with axis is none [[[26  6 13 44]
  [24  3  6 37]
  [16  6 22 14]
  [47  1 42 50]
  [48 50 50 22]
  [ 5 48 36 22]]

 [[37 29 19 23]
  [22 50  5 32]
  [27 30 18 21]
  [ 2  8 34 12]
  [31 24 23 21]
  [ 4 47 38 27]]]

 stack with axis is 0 [[[26  6 13 44]
  [24  3  6 37]
  [16  6 22 14]
  [47  1 42 50]
  [48 50 50 22]
  [ 5 48 36 22]]

 [[37 29 19 23]
  [22 50  5 32]
  [27 30 18 21]
  [ 2  8 34 12]
  [31 24 23 21]
  [ 4 47 38 27]]]

 stack with axis is one [[[26  6 13 44]
  [37 29 19 23]]

 [[24  3  6 37]
  [22 50  5 32]]

 [[16  6 22 14]
  [27 30 18 21]]

 [[47  1 42 50]
  [ 2  8 34 12]]

 [[48 50 50 22]
  [31 24 23 21]]

 [[ 5 48 36 22]
  [ 4 47 38 27]]]



In [34]:
#joining array

#vertical stack

ma = [r.randint(0,50) for i in range(24)]
ma = np.array(ma).reshape(6,4)
print(ma)
print()
mb = [r.randint(0,50) for i in range(24)]
mb = np.array(mb).reshape(6,4)
print(mb)
print()

#vertical_stack:

v_stc = np.vstack((ma,mb))
print("vertical stack:",v_stc)
print()

#horizontalstack
h_stc = np.hstack((ma,mb))
print("vertical stack:",h_stc)
print()


[[39  1 33 31]
 [13 14  5  9]
 [43 35  1 39]
 [ 2  4  2  9]
 [14 17 13 26]
 [50 50  4 12]]

[[ 7 47 45 20]
 [16  8  4 20]
 [ 8 25 21 27]
 [ 8 12 15  1]
 [24 30 22 40]
 [22 48 49 20]]

vertical stack: [[39  1 33 31]
 [13 14  5  9]
 [43 35  1 39]
 [ 2  4  2  9]
 [14 17 13 26]
 [50 50  4 12]
 [ 7 47 45 20]
 [16  8  4 20]
 [ 8 25 21 27]
 [ 8 12 15  1]
 [24 30 22 40]
 [22 48 49 20]]

vertical stack: [[39  1 33 31  7 47 45 20]
 [13 14  5  9 16  8  4 20]
 [43 35  1 39  8 25 21 27]
 [ 2  4  2  9  8 12 15  1]
 [14 17 13 26 24 30 22 40]
 [50 50  4 12 22 48 49 20]]



In [41]:
#   Spliting of array

ma = [r.randint(0,50) for i in range(24)]
ma = np.array(ma).reshape(6,4)
print(ma)
print()

# split()

spl = np.split(ma,6)
print(" stack with axis is none",spl)
print()

# hsplit()

hspl = np.hsplit(ma,4)
print(" stack with axis is none",hspl)
print()

# vsplit()

vspl = np.vsplit(ma,6)
print(" stack with axis is none",vspl)
print()




[[49 48 22 39]
 [19 28 29 26]
 [47  5 22  3]
 [18 19 31 16]
 [20 35 37  0]
 [24 46  3 25]]

 stack with axis is none [array([[49, 48, 22, 39]]), array([[19, 28, 29, 26]]), array([[47,  5, 22,  3]]), array([[18, 19, 31, 16]]), array([[20, 35, 37,  0]]), array([[24, 46,  3, 25]])]

 stack with axis is none [array([[49],
       [19],
       [47],
       [18],
       [20],
       [24]]), array([[48],
       [28],
       [ 5],
       [19],
       [35],
       [46]]), array([[22],
       [29],
       [22],
       [31],
       [37],
       [ 3]]), array([[39],
       [26],
       [ 3],
       [16],
       [ 0],
       [25]])]

 stack with axis is none [array([[49, 48, 22, 39]]), array([[19, 28, 29, 26]]), array([[47,  5, 22,  3]]), array([[18, 19, 31, 16]]), array([[20, 35, 37,  0]]), array([[24, 46,  3, 25]])]

