<a href="https://colab.research.google.com/github/demigod1208/numpy-practice/blob/main/Day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# creation array using existing data and isnan()
import numpy as np

a = np.arange(0,9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
d = [-1,-1,0]
e = np.array(d)
c = np.isnan(e)
print(c)
print()
print(e)
print()
print(type(e))

[False False False]

[-1 -1  0]

<class 'numpy.ndarray'>


In [30]:
#aggregiate function

cars = np.loadtxt("/content/marks.csv",delimiter=',',usecols=(5),skiprows=1)
print(cars)
print()

maximum = cars.max()
print(maximum)
print()

minimum = cars.min()
print(minimum)
print()

means = cars.mean()
print(means)
print()

s_d = cars.std()
print(s_d)
print()

total_values = cars.sum()
print(total_values)
print()

al = np.all(cars)
print(al)

[420. 280. 350. 269. 317. 470. 333. 365. 305. 350. 460. 474. 409. 377.
 415. 382. 298. 462. 370. 313. 464. 302. 252. 259. 308. 392. 424. 403.
 370. 328. 398. 434. 291. 472. 263. 439. 464. 449. 401. 364. 296. 292.
 438. 357. 331. 317. 429. 407. 321. 274. 447. 274. 437. 411. 257. 310.
 396. 270. 311. 459. 378. 316. 283. 266. 381. 409. 313. 306. 448. 348.
 292. 400. 352. 441. 428. 309. 441. 439. 264. 281. 302. 432. 423. 336.
 383. 321. 469. 270. 341. 281. 403. 333. 323. 348. 345. 397. 449. 261.
 456. 370. 322. 379. 446. 404. 301. 254. 351. 444. 264. 286. 463. 273.
 316. 324. 465. 398. 324. 340. 414. 346. 408. 332. 394. 474. 398. 262.
 410. 391. 444. 461.]

474.0

252.0

364.2769230769231

66.17947803971762

47356.0

True


In [63]:
cars = np.loadtxt("/cars.csv",delimiter=",",usecols=(29),skiprows=2)
print(cars)
print()
print(type(cars))
maximum = cars.max()
print(maximum)
print()

minimum = cars.min()
print(minimum)
print()

means = cars.mean()
print(means)
print()

s_d = cars.std()
print(s_d)
print()

total_values = cars.sum()
print(total_values)
print()

al = np.all(cars)
print(al)
print()

i = np.array([[2,3,89],[77,98,9],[30000,10000,900]])
print(cars[i])
print()



[ 83. 151.  86. ... 369. 490. 632.]

<class 'numpy.ndarray'>
2232.0

0.0

80.57892551258759

112.82608898549202

3104706.0

False

[[ 86.   7.  35.]
 [ 58.  10.  11.]
 [152.  82.   5.]]



In [17]:
# logic function:Testing Array Type
# np.iscomplex()
# np.isreal()

import numpy as np

z = np.array( [ 2j+1, 9j-8, 7j+9, 9j-7, 0j+6 , 90 ] )
x = np.array( [2,12,23,445,878,0,3+1j] )

np_real = np.isreal(x)
print(np_real)
print()

np_complex = np.iscomplex(z)
print(np_complex)

[ True  True  True  True  True  True False]

[ True  True  True  True False False]


In [ ]:
# Logic function : testing truth value
# np.any()
# np.all()

import random as r
x = []
y = []
i = 0
for i in range(10):
    b = r.randrange(10,33)
    x.append(b)


x1 = np.array(x)
print(x1)
print()

np_all = np.all(x1)
print(np_all)
print()

np_any = np.any(x1)
print(np_any)
print()

[26 18 20 20 24 28 20 28 14 12]

True

True



In [ ]:
# Logic Functions:Logical Operation
import numpy as np
import random as r

x = []
i = 0
for i in range(10):
    b = r.randrange(10,33)
    x.append(b)


x1 = np.array(x)
print(x1)
print()

n_t = np.logical_and(x1>10,x1<50)
print(n_t)
print()

o_o = np.logical_or(x1>10,x1<50)
print(o_o)
print()

x_o = np.logical_xor(x1>10,x1<50)
print(x_o)
print()

n_o = np.logical_not(x1>10,x1<50)
print(n_o)
print()

[16 25 30 30 13 20 14 25 17 15]

[ True  True  True  True  True  True  True  True  True  True]

[ True  True  True  True  True  True  True  True  True  True]

[False False False False False False False False False False]

[False False False False False False False False False False]



In [72]:
#Slicing

import numpy as np

a = np.arange(10)
a_slice = slice(1,8,1)
print(a[a_slice])
print()
print(a[3:])
print()
print(a[:7])
print()
print(a[2:5])

[1 2 3 4 5 6 7]

[3 4 5 6 7 8 9]

[0 1 2 3 4 5 6]

[2 3 4]


In [91]:
#slicing in multidimensionla array
a = np.arange(1,10).reshape(3,3)
print(a)
print()
b = a[0:3,0:2]
print(b)
print()
four = np.random.randint(0,30,(4,4))
print(four)
print()
sli = four[2:4,2:4]
print(sli)
print()
slicing = four[1:2,1:4]
print(slicing)
print()
slicer = four[1:4,1:4]
print(slicer)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]]

[[17  3  4 15]
 [24 14  2 27]
 [15 18 29  2]
 [20 25 26 24]]

[[29  2]
 [26 24]]

[[14  2 27]]

[[14  2 27]
 [18 29  2]
 [25 26 24]]



In [80]:
# nditer()

x = np.array([[2,3,89],[77,98,9],[30000,10000,900]])
print(x)
print()
a = np.nditer(i)
for i in a:
  print(i)

# we can also do it by loop

for b in x:
  for c in b:
    print(c)

[[    2     3    89]
 [   77    98     9]
 [30000 10000   900]]

900
2
3
89
77
98
9
30000
10000
900
