<a href="https://colab.research.google.com/github/demigod1208/numpy-practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import random as r
import sys

list1 = [r.randint(1, 100) for i in range(10)]

print(list1)

print(f"Size of each element of list in bytes: {sys.getsizeof(list1[0])}")
print(f"Size of the whole list in bytes: {sys.getsizeof(list1)}")

array1d = np.array(list1,ndmin=1)
print(array1d)

print(f"Size of each element of the 1-D array in bytes: {array1d.itemsize}")
print(f"Size of the whole 1-D array in bytes: {array1d.nbytes}")

array2d = np.array(list1,ndmin=2)
print(array2d)

print(f"Size of each element of the 2-D array in bytes: {array2d.itemsize}")
print(f"Size of the whole 2-D array in bytes: {array2d.nbytes}")

array3d = np.array(list1,ndmin=3)
print(array3d)

print(f"Size of each element of the 3-D array in bytes: {array3d.itemsize}")
print(f"Size of the whole 3-D array in bytes: {array3d.nbytes}")


[30, 24, 93, 63, 28, 78, 54, 27, 5, 23]
Size of each element of list in bytes: 28
Size of the whole list in bytes: 184
[30 24 93 63 28 78 54 27  5 23]
Size of each element of the 1-D array in bytes: 8
Size of the whole 1-D array in bytes: 80
[[30 24 93 63 28 78 54 27  5 23]]
Size of each element of the 2-D array in bytes: 8
Size of the whole 2-D array in bytes: 80
[[[30 24 93 63 28 78 54 27  5 23]]]
Size of each element of the 3-D array in bytes: 8
Size of the whole 3-D array in bytes: 80


In [6]:
import numpy as np

a = np.arange(1,30,2)
print(f"{a}")
type(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


numpy.ndarray

In [99]:
import numpy as np
import random as r
import sys as ss

# creation of list by creating by random values

list1 = [r.randint(1, 100) for i in range(10)]
list2 = [r.randint(1, 100) for i in range(10)]
list3 = [r.randint(1, 100) for i in range(10)]

#finding the total size of the list "we need to import system modules for this"
def list_size():
  list1_size = ss.getsizeof(list1)
  list2_size = ss.getsizeof(list2)
  list3_size = ss.getsizeof(list3)
  print(list1_size)
  print(list2_size)
  print(list3_size)
  print(2 * "\n")
# creation of array by zeros and ones

s_1 = np.zeros((5,2))
print(s_1)

s_0 = np.ones((3,5))
print(s_0)
print(2 * "\n")

# giving two aruguments
s_11 = np.zeros((5,2),dtype=int)
print(s_11)

s_00 = np.ones((3,5),dtype=float)
print(s_00)
print(2 * "\n")


#creation of array by numerical values

def num_values():
  arr = np.arange(0,10)
  arr1 = np.arange(0,100,7) # giving step values
  print(arr)
  print(arr1)
  lin = np.linspace(1,10,10)
  print(lin)
  lin1 = np.linspace(1,50,100) # create a ndarray in the arange 1 to 50 total elements of 100
  print(lin1)

#creation of array by exixting
a = np.array(list1,ndmin=2)
w = np.array(list2,ndmin=2)
s = np.array(list3,ndmin=2)
print(a)
print(w)
print(s)
print(2 * "\n")

# copy function in array creating existing
li1 = np.copy(a)
li2 = np.copy(w)
li3 = np.copy(s)

# reshape the array
def reshaping():
  rs1=li1.reshape(5,2)
  rs2=li2.reshape(5,2)
  rs3=li3.reshape(5,2)
  print(rs1)
  print(rs2)
  print(rs3)

# finding the dimensions of ndarray
def no_dimensions():
  nd1 = li1.ndmin()
  nd2 = li2.ndmin()
  nd3 = li3.ndmin()
  print(nd1)
  print(nd2)
  print(nd3)

# converting elements in to opposite symbol
def negative_con():
  l1 = li1.__neg__()
  l2 = li2.__neg__()
  l3 = li3.__neg__()
  print(l1)
  print(l2)
  print(l3)

# compare the specific value
def compare():
  liss1 = li1.__eq__(50)
  liss2 = li2.__eq__(50)
  liss3 = li3.__eq__(50)
  print(liss1)
  print(liss2)
  print(liss3)

# find the power of each elements
def power():
  global lis1
  lis1 = li1.__pow__(2)
  lis2 = li2.__pow__(2)
  lis3 = li3.__pow__(2)
  print(lis1)
  print(lis2)
  print(lis3)

# finding the  total size of array
def total_bytes():
  lis1tb = lis1.nbytes
  print(lis1tb)
  print()
  li1tb = li1.nbytes
  print(li1tb)
  print()
  li2tb = li2.nbytes
  print(lis1tb)
  print()
  lis3tb = lis3.nbytes
  print(lis3tb)
  print()
  s_1tb = s_1.nbytes
  print(lis1tb)
  print()
  s_0tb = s_0.nbytes
  print(lis1tb)
  print()
  s_11tb = s_11.nbytes
  print(s_11tb)
  print()
  s_00tb = s_00.nbytes
  print(s_00tb)

#finding size of each element
def sizes():
  li1s = li1.itemsize
  print(li1s)
  print()
  s_0s = s_0.itemsize
  print(s_0s)
  print()
  s_1s = s_1.itemsize
  print(s_1s)
  print()
  s_00s = s_11.itemsize
  print(s_00s)
  print()
  lis1s=lis1.itemsize
  print(lis1s)

list_size()
print(2 * "\n")
num_values()
print(2 * "\n")
negative_con()
print(2 * "\n")
compare()
print(2 * "\n")
power()
print(2 * "\n")
reshaping()
print(2 * "\n")
total_bytes()
print(2 * "\n")
sizes()






[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



[[36 29 30 19 47 92 11 20 19 96]]
[[83 96 28 29 54 17 29 27 11 87]]
[[ 30  71 100  73   8  87  12  38  34  39]]



184
184
184






[0 1 2 3 4 5 6 7 8 9]
[ 0  7 14 21 28 35 42 49 56 63 70 77 84 91 98]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.2727272